### ISSUE TITLE
Where are the poor people page cross checks

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#101]
http://212.71.254.23:9999/where-are-the-poor
 
All looks fine to me.

**Comment by kb4777** [comment]
Hi @epicallan , thanks for this! Looking good and ready for a detailed check @BeckyWillmoth. I've spotted a few small visual issues (see below) but nothing high priority:

- [ ] The title is too near to the top red bar 
- [ ] The text should go onto a new line after 'half.' From 'Explore plausible poverty...' onwards
- [ ] I assume the font change is intentional as part of the new branding?
- [ ] The last sentence of the paragraph under the **'About this visualisation'** heading should be on a new line. From 'Data accessed from source: 20 August 2013.'
- [ ] There needs to be more white space after the **'About the data'** paragraph

**Comment by kb4777** [comment]
Adding these issues from Remi's check, not for fixing immediately just so that we have them all here:

- [ ] Font style/size changes. Assume this is the rebrand?
- [ ] Too much space between the visualisation and the buttons
- [ ] Switching between the scenarios (worst, baseline, best case) the visualisation moves in erratic ways, and the end picture doesn't look right. E.g. 
![image](https://user-images.githubusercontent.com/25456036/29873924-f72083f2-8d8c-11e7-8855-5a8d1ec05e47.png)
- [ ] When switching from 'global' to 'regional' the original site first moves the icons, then the numbers/headings appear. On staging the numbers appear first, which doesn't look quite right. Same when switching back

**Comment by epicallan** [comment]
closed in favour of https://github.com/devinit/datahub/issues/142
