### ISSUE TITLE
Spotlight on Uganda district level checks

### ISSUE THREAD

**Issue by BeckyWillmoth** [devinit/datahub#126]

**Comment by remilsg** [comment]
**Top Paragraph and 5 banner tabs (Overview, Poverty...)**

- [ ] HIGH for some questions, the live website shows 'no data', whereas staging shows some data: the table shows the data found in the staging website, for these questions;
![cheeky table kotido c kdo tmtc](https://user-images.githubusercontent.com/31883624/30430643-c042b648-9953-11e7-9276-7f251a1bfbbc.PNG)

- [ ] HIGH- data differs between the 2 versions for following questions: 'Primary Leaving Exam: Overall Ranking'; 'District League Health Performance Score: Overall Ranking'                                                                                                                

- [ ] HIGH - 'Poverty', "% of People under national poverty line': district name must be capitalised (currently shows: 'HOW MANY PEOPLE IN Arua LIVE BELOW THE NATIONAL POVERTY LINE ?)                                                                       

- [ ] Urban vs. Rural Split: MEDIUM -  should be written differently (same issue as country profiles: Urban should be written in red, and rural in blue)     
                                    HIGH - values don’t come up when hovering over the graph ‘Urban vs. Rural split’                               
MEDIUM - need to arrange 'average dependency ratio' display so that the banner looks overall symmetric; currently does not line up nicely
![dependency ratio](https://user-images.githubusercontent.com/31883624/30431971-245957d2-9958-11e7-94ff-2cfa70e4250d.PNG)

Information buttons:                                                                             
- [ ] HIGH- content of the info box does not correspond to data shown for: 'what resources are available...?'; '% of students passing primary exam: place overall'; 
- [ ] HIGH- Currency dropdown button changes the data  for the revenue & expenditure parts, but not for top banner tabs: _is this normal ?_

**Revenue & Expenditure Headings**

- [ ] MEDIUM - rounding for the percentages in the boxes is different: live version -> 1 decimal point; staging -> Integer

- [ ] HIGH - same problem with the ring as for country profiles                                    

- [ ] MEDIUM- scale on the y axis is not the same: line chart's shape is very different (much flatter - a bit too flat)            

- [ ] MEDIUM- in the line chart, values on the y axis should be shown at more regular intervals when currency is UGX                                                                                                                      

- [ ] HIGH- expenditure large header does not appear (see screenshot to understand what I mean by 'large header')        
![expenditure large header](https://user-images.githubusercontent.com/31883624/30430872-8d4e98aa-9954-11e7-8266-6b2072d8d3d5.PNG) 

- HIGH in live version, there is generally data for expenditure from 2012 onwards; in staging version, only for 2013 onwards (notice that in both versions, data for revenue starts from 2013)
HIGH - Twitter, facebook, email and share chart view buttons don't appear (although they should do, at the bottom of the page)               

Legend     
- [ ] HIGH - live version: only necessary legend titles are shows, others are hidden
- [ ]  MEDIUM spacing of the words in the legend is too tight +font colour is too dark
- [ ] LOW - live version: legend titles below the boxes are arranged by alphabetic order, which looks better/tidier
![white base to copy paste](https://user-images.githubusercontent.com/31883624/30431655-32449592-9957-11e7-9762-947fa609d209.PNG) 
                                                                                                                                                                                                                         
**Other General Comments**

- [ ] HIGH - only one data source appears at the bottom of the page + download links don't work                                                                                                                          

- [ ] HIGH - when switching from one district to another, tab name does not change 
![arua - amuru](https://user-images.githubusercontent.com/31883624/30431806-b5303d3a-9957-11e7-813d-2b5070a7eb7f.PNG)

**Comment by kb4777** [comment]
Hi @epicallan , here are some visual/branding  checks from @RebeccaHills : 

- [ ] Overview tab – middle pie chart – orange and red look v similar. As we only have 3 colours on this can we use something different? Green?
- [ ] Population tab – middle chart – legend text should not be in bold
- [ ] Revenue tree map – the same colours are being used for different categories – can this change?
- [ ] Tree maps – we aren’t using the brighter colours – can we switch to the secondary palette colours (Colour #s)?
- [ ] Tree maps – legend font is incorrect
- [ ] Same issue as mentioned before (on country profiles) about the years in circles on sticks – black outline and gap between line and circle.
