### ISSUE TITLE
Leave for now list

### ISSUE THREAD

**Issue by kb4777** [devinit/datahub#133]
Everything outstanding, that does not need to be done before going live

- [ ] google analytics events tracking for downloads

**Comment by remilsg** [comment]
Spotlight on Uganda - Map

- [ ] LEAVE FOR NOW Can the number format of the top/bottom 10 lists be made like the global picture, and add in .0 to whole numbers where they are being compared with decimals, so that they line up. (The old SoU does not do this but would be good for internal consistency) (this only works for % values for the rest its much more work than necessary and may not be scaleable, discussed with @BeckyWillmoth )
Still issue for:
Average household size
Primary pupils with adequate sitting and writing space-all schools (%)
Primary pupils with adequate sitting and writing space-government schools (%)

- [ ] LEAVE FOR NOW As with the Global Picture, visually the lists are different. The columns are closer together in the middle of the page, and the rows are more spread out.

- [ ] Same as Global Picture, the sentence structure and use of units in the tooltips box varies across the maps. Please always put the unit in the white text at the start, with no unit in the orange next to the number.
LEAVE FOR NOW - The unit is not shown in the tooltip for the following maps:
Diphteria treatment coverage rate
Tetanus Vaccine Coverage Rate
Antenatal Care Coverage Rate
The unit (%) is shown twice for most maps for which the title of the map is in the format 'Title of the Map, (%)' e.g 'Approved Posts that are filled, (%)'; 'Urban Population, (%)'; 'Rural Access to Safe Water (%)'; ...
(two exceptions: 'secondary pupils with adequate seating/writing space [all schools]'; 'secondary pupils with adequate seating/writing space [gov schools]')

- [ ] LEAVE FOR NOW The first map you land on is 'Urban population' but with a drop down title that says 'Average household size'. The first in list is 'Average household size' so it should land on this
This is half fixed, but still isn't landing on the top map in the list
(**The spotlight maps have default indicators and the default indicator is not necessary the first in the list and this is the way it is on the live site. I can change it to match what you are suggesting. cc @BeckyWillmoth **)

- [ ] LEAVE FOR NOW Old issue: Three maps are named inconsistently (2nd, 3rd and 4th in drop down list), which for two of them is misleading as it misses out the % unit and so is hard to understand. Can these titles be renamed? Happy to do it myself in the relevant csv, if that can be sent to me. Thanks
This hasn't been done but I'll leave it ticked as it's an existing issue. Will add to a different list

**Comment by remilsg** [comment]
Global Picture

- [ ] LEAVE FOR NOW indicators dropdown arrow not matching live

- [ ] LEAVE FOR NOW slider not very responsive at initial scrolling, seems laggy / hard

- [ ] LEAVE FOR NOW (perhaps align the numbers to the left instead of adding a dp?) For decimals in the top/bottom 10 lists, if the number ends with a 0 it show less decimal places. E.g. 12.20 becomes 12.2. This means numbers are not aligned with the rest of the values. Please can the 0’s be added back in (as on the current live site).
**From Katie: this has been fixed for some maps but not others. E.g. FDI per person:**
![image](https://user-images.githubusercontent.com/25456036/30106481-7c855e4e-92f3-11e7-81b5-e23ccceb51fe.png)


- [ ] LEAVE FOR NOW Additional issues with the i button pop up. The size and shape of the box is wrong, plus too much white space, and the font used for the source is too big.

- [ ] LEAVE FOR NOW For all maps there should be a hover box that says 'no data' when there is no data. At present nothing happens.
**From Katie: This has been partially fixed. However the long sentence describing the indicator is still there, which looks messy. Preference would be for box to only show Flag, Country name, ‘No data’ (as on old site) Fix now if easy, otherwise leave for later**

- [ ] LEAVE FOR NOW When scrolling between years, the map changes are slower on the new site compared to the live one. 
**Much better but when scrolling the colours take a long time to catch up with the slider**

- [ ] LEAVE FOR NOW The sentence structure and use of units in the tooltips box varies across the maps. This needs to be made uniform. Also for Spotlights. Please always put the unit in the white text at the start, with no unit in the orange next to the number. (E.g. in 'International Official Finance' maps there is an additional orange 'US$:' in front of the value in the tooltips. This should not be there)
**From Katie: There are still orange % signs in the tooltips box. This wouldn’t matter too much but in the Government finance maps the words [actual] or [proj] appear in between value and % and that looks wrong**

- [ ] LEAVE FOR NOW - For the '% of people in the P20 (subnational level)' the legend is different, with an extra category (<10%). Was there a reason for this change? If not, we should stick to replication of original.

- [ ] LEAVE FOR NOW The share chart white box is a lot bigger than it used to be and doesn’t look as good oversized

**Comment by remilsg** [comment]
## Unbundling Aid

### General 

-	hover  box sometimes stays 'stuck' in the graph when I move the mouse to somewhere else on the page (add screenshot if possible/relevant)

### Landing Page
-	staging v: font is much smaller for the sentence 'explore and compare...'

-	font is also smaller for the rest (or is it a choice?)

-	source: in staging version, 'DI based on OECD DAC data' is written in bold

-	on the top-right corner, possible to see the top of the 'compare' button

### Second Page (after having clicked ‘explore’)
-	Landing year is different: live -> 2014; staging -> 2010

-	Boxes are arranged in a different way: live -> smallest amount in bottom-right corner
                                                                                   Staging -> smallest amount on top-right corner

-	When clicking on a dropdown, other dropdown options don’t disappear (add screenshot)
-	2015 does not appear in the year dropdown
-	i button and ‘using this visualisation’ are not present
-	facebook and twitter hyperlinks don’t work
-	popo-up appears when clicking on ‘share this chart’, but no hypoerlink in the box

**Comment by remilsg** [comment]
## Spotlights on Uganda - Districts 
- [ ] LEAVE FOR NOW - MEDIUM - need to arrange 'average dependency ratio' display so that the banner population looks overall symmetric; currently does not line up nicely
this is also true for the banner poverty
![dependency ratio](https://user-images.githubusercontent.com/31883624/30431971-245957d2-9958-11e7-94ff-2cfa70e4250d.PNG)

- [ ] LEAVE FOR NOW - content of the info box does not correspond to data shown for: 'what resources are available...?'; '% of students passing primary exam: place overall'; 
**The correct info doesn't exist at the moment, we could ask some one to add it or leave as is since there is going to update on the same in few weeks**

- [ ] LEAVE FOR NOW - MEDIUM- in the line chart, values on the y axis should be shown at more regular intervals when currency is UGX        

- [ ] LEAVE FOR NOW - Twitter, facebook, email and share chart view buttons don't appear (although they should do, at the bottom of the page)             

- [ ]  MEDIUM spacing of the words in the legend is too tight +font colour is too dark
- [ ] LEAVE FOR NOW - live version: legend titles below the boxes are arranged by alphabetic order, which looks better/tidier
![white base to copy paste](https://user-images.githubusercontent.com/31883624/30431655-32449592-9957-11e7-9762-947fa609d209.PNG)

**Comment by remilsg** [comment]
## Country Profiles

- [ ] LEAVE FOR NOW (this is much better than it was) The year slider is too tall on the ‘flows over time’ chart + there should be no border on the year ring + top of the ring is cut off + there is a gap between the circle/ring and the line
the border on the year ring is still present on the inflows vs. outflows graph

- [ ] Tab 'International Resources', flows over time:  LEAVE FOR NOW the sub-heading text (value, %) in the boxes appears smaller in the staging version, so it is harder to read

- [ ] LEAVE FOR NOW the header ‘financing’ appears below the graph (in both versions): does not look right

**Comment by remilsg** [comment]
## Unbundling Aid

- [ ] staging v: font is much smaller for the sentence 'explore and compare...'

 

- [ ] font is also smaller for the rest (or is it a choice?)

- [ ]  on the top-right corner, possible to see the top of the 'compare' button

- [ ] Boxes are arranged in a different way: live -> smallest amount in bottom-right corner
Staging -> smallest amount on top-right corner

- [ ] When clicking on a dropdown, other dropdown options don’t disappear

- [ ] facebook and twitter hyperlinks don’t work

- [ ] hover box sometimes stays 'stuck' in the graph when I move the mouse to somewhere else on the page (add screenshot if possible/relevant)
