### ISSUE TITLE
High priority

### ISSUE THREAD

**Issue by kb4777** [devinit/datahub#134]
Everything that needs doing before going live

**Comment by remilsg** [comment]
- [ ] HIGH for some questions, the live website shows 'no data', whereas staging shows some data: the table shows the data found in the staging website, for these questions;
![cheeky table kotido c kdo tmtc](https://user-images.githubusercontent.com/31883624/30430643-c042b648-9953-11e7-9276-7f251a1bfbbc.PNG)

**Comment by remilsg** [comment]
Whole Site 

- [ ] browser cache issue that requires one to refresh the page on new site update

**Comment by remilsg** [comment]
Global Picture 

- [ ] Adjust gradients on all heatmaps so transition between middle colour and lightest and darkest are smoother. Some of the lightest shades could also be a little lighter (for example for humanitarian finance how does it look if we adjust lightest blue to blue 7 #bcd4f0?) (applies to all heatmaps)
From Katie: I've spoken to Bex and this is still a problem. She said that the screen shot you showed her was good, but this hasn't come through to the version here http://212.71.254.23:8080/
Waiting final confirmation, but think this is ok now

**Comment by remilsg** [comment]
Unbundling Aid

- [ ] data is rounded at every stage, and then the rounded data is summed to calculate more 'general data'          
-> this leads to a 200m difference on total ODA flows in 2015. 
![b8bd6a68c4d2676303b994bd2aea66bbe233f6afd34d41b6f0 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/31883624/30924442-a2bd5cec-a3a6-11e7-8595-de9046750cbd.jpg)

**Comment by remilsg** [comment]
## Spotlights on Uganda - Districts

- [ ] HIGH for some questions, the live website shows 'no data', whereas staging shows some data: the table shows the data found in the staging website, for these questions;
![cheeky table kotido c kdo tmtc](https://user-images.githubusercontent.com/31883624/30430643-c042b648-9953-11e7-9276-7f251a1bfbbc.PNG)

**The data thats being shown is actually right. It was not being fetched on live due to some errors / issues. We just need to crosscheck with @wilbrodn if its right. cc @BeckyWillmoth**

- [x] HIGH- data differs between the 2 versions for following questions: 'Primary Leaving Exam: Overall Ranking'; 'District League Health Performance Score: Overall Ranking'      
**there was an error in the way rankings were done on the live, what we have is correct i can get you a sample of the raw data if you would like to cross check**                                                                                                          

- [x] HIGH - 'Poverty', "% of People under national poverty line': district name must be capitalised (currently shows: 'HOW MANY PEOPLE IN Arua LIVE BELOW THE NATIONAL POVERTY LINE ?)                                                                       

- [x] Urban vs. Rural Split: MEDIUM -  should be written differently (same issue as country profiles: Urban should be written in red, and rural in blue)     
- [x] HIGH - values don’t come up when hovering over the graph ‘Urban vs. Rural split’  

- [x] HIGH- Currency dropdown button changes the data  for the revenue & expenditure parts, but not for top banner tabs: _is this normal ?_

- [x] HIGH- expenditure large header does not appear (see screenshot to understand what I mean by 'large header')   
**it has been 'replacewd' by a liarge header 'Revenue and Expenditure'**     
![expenditure large header](https://user-images.githubusercontent.com/31883624/30430872-8d4e98aa-9954-11e7-8266-6b2072d8d3d5.PNG) 

- [x] HIGH in live version, there is generally data for expenditure from 2012 onwards; in staging version, only for 2013 onwards (notice that in both versions, data for revenue starts from 2013)
** The fact that there was no corresponding revenue values for 2012, we decided to start from 2013 since the lack of them was breaking the chart. Wilbrod was fine with this.**

- [ ] HIGH - only one data source appears at the bottom of the page + download links don't work

**Comment by remilsg** [comment]
## Country Profiles

- [ ] data sources (bottom of the page): only one appears in staging version

- [ ] UAE: Data is different between live and staging version

 

- [ ] i buttons (info boxes): - 'income distribution per quintile': shows a different year (e.g. shows ‘data is for 2015...’ instead of ‘for 2014’)
- ‘what is the total population’: year when the data was extracted is not precised in the info box (i.e. the sentence 'data is for XXXX' does not appear)
Remi: 2nd issue (total poulation) has not been adressed

**Comment by remilsg** [comment]
# Other Visualisations
## Unbundling OOFs

- [ ] When clicking on ‘Unbundling OOFs’, the tab displays ‘Unbundling Aid’ 
 + Text is the same as for unbundling Aid 
 +  info box is wrong
 +using this visualization button (just the text at the bottom-left corner, probably not what matters most) 
Data is right though !
![screen shot 2017-09-29 at 10 26 19](https://user-images.githubusercontent.com/31883624/31008621-0f7b8c3c-a505-11e7-9049-a82bc4050229.png)

- [ ] Above the Table, rectangular (horizontal) box showing Total Gross Disbursements: live -> 2012 prices; staging -> 2015 prices 
       Is it actually the case ?

**Comment by remilsg** [comment]
## Unbundling Aid

- [ ] colour is not right
change from clour choice 5 to colour choice 1, except when there is the same colour twice (e.g. blue): in this case, use colour choice 1 and one other
