### ISSUE TITLE
Add missing d3 charts in the visbox charting library

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#27]
Missing charts for use with DH

- [x] bubble chart
- [ ] tree maps
- [x] area chart

**Comment by akmiller01** [comment]
Hi Allan,

Done with the area chart https://github.com/devinit/charts/commit/621ad4a8022c4a17171c6a534f17cf45931bb6b6 and the bubble chart https://github.com/devinit/charts/commit/afaf58d5841fc65b9453cc3f659a9b7d27af4a36 but conceptually I'm struggling a bit with the tree charts, because it's fundamentally a hierarchical-data vis, and so far the Vis-box has been built on flat data files. We could have a pre-defined level of depth (e.g. Groupby1, Groupby2, Groupby3), but that might be needlessly complex and not flexible enough for what we want.

**Comment by akmiller01** [comment]
Unless we just want the Visbox to draw 1-layer deep treecharts, and let the Datahub stitch layers together.

**Comment by epicallan** [comment]
Hi @akmiller01 
I think visbox should only draw 1 layer and datahub stitches things up. 
Thanks for the progress. Looks good.

**Comment by akmiller01** [comment]
Boom. https://github.com/devinit/charts/commit/624f06f0c3b1b613160c467b8f934fee9f90f525 And it's got an option to pick a numerical colour scale, to make the 2D tree charts we use for other publications.
