### ISSUE TITLE
Countries showing up as "false"

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#352]
## I'm submitting a bug...

**Describe the Issue**
When mouse is hovering around map, ‘false’ comes up.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Global Picture'
2. Click on ‘Poverty’ Tab.
3. Scroll down on drop-down menu and click on '% of people in the P20 [Subnational Level]'
4. Scroll down to see map
5. Several countries show up as "false"

**Expected Behaviour**
Either a country name or no ‘False’ bubble showing up

**Screenshots/GIF**
﻿﻿﻿﻿
![screen shot 2018-07-27 at 10 22 09](https://user-images.githubusercontent.com/36768381/43313073-f4ad93ea-9186-11e8-8740-73d4d1107368.png)

**Desktop (please complete the following information):**
 - OS: [X] Mac 10.13.6
 - Browser [X]  Firefox
 - Version [X]

**Comment by edwinmp** [comment]
Hi @k8hughes @Duncan-Knox, while debugging this chat, I discovered that while the map is already drawn to show the different p20 concentrations based on colour, there is no data for this particular indicator, as well as the one after it `% of people in the P20 (survey level)`

**Comment by k8hughes** [comment]
This sounds like one for @Duncan-Knox ...

**Comment by akmiller01** [comment]
@edwinmp since the subnational and survey level shapes were so complex, these two data sources were hardcoded into the tileserver itself here http://178.79.185.236:8080/ and Github here: https://github.com/devinit/di-tileserver

Thankfully I left myself instructions on how to rebuild the MBtiles files, so we should be able to correct mistakes in the data, but it would probably take me a full day to do so. Are you sure this is a problem with the underlying data and not with the code for the variables that the map is attempting to query? If we can correct what the map is trying to grab, that would be much easier than rebuilding the MBtiles.

**Comment by akmiller01** [comment]
Maybe the confusion is stemming from the fact that in the Subnational layer, the variable is called "P20" and in the dot layer the variable is called "p20."

![image](https://user-images.githubusercontent.com/2836840/43650320-778aa88a-970d-11e8-969a-4687d0c7d536.png)

![image](https://user-images.githubusercontent.com/2836840/43650345-8547ac0c-970d-11e8-99cf-e07c33870432.png)

**Comment by k8hughes** [comment]
@edwinmp what do you think?

**Comment by k8hughes** [comment]
SGTM
@akmiller01 is there any update to the data for this?  If there is no database table why is that?

**Comment by akmiller01** [comment]
We could update the data, Zach and I just re-ran most of the figures. It
would probably take a few days to re-render the maps with it.

These don't exist as data tables because the longitude and latitude are
under a data agreement where we cannot publically release them, and
stripped from the longitude and latitude the data isn't useful.

And even if we had data tables, the map was not configured to dynamically
display the subnational shapes or cluster dots, so the only way to display
them was with this baked-in style.

**Comment by edwinmp** [comment]
@k8hughes Have opted for the more descriptive message below... what do you think?
<img width="991" alt="screenshot" src="https://user-images.githubusercontent.com/5672438/43942521-0843b25e-9c81-11e8-8ec7-69accdd55df0.png">

**Comment by k8hughes** [comment]
LGMT.

 @akmiller01 if there is new data then we can create a new issue to update it.

**Comment by edwinmp** [comment]
@akmiller01 It didn't have values. Simply showed the map, and on hover, it showed a [tooltip](https://user-images.githubusercontent.com/36768381/43313073-f4ad93ea-9186-11e8-8740-73d4d1107368.png) with "false" in it as shown in the initial issue comment.
If it was meant to pull values from the tile server, then I'll have to look into how it's supposed to do that. Thought the tile server only rendered maps but the data came from elsewhere.

**Comment by akmiller01** [comment]
@edwinmp , the tooltip worked when we implemented these maps. I'm guessing it got broken in the move over to React. I'm stuck on a train right now but I can help you debug when I get into the office.

The data is delivered along with the tileserver in JSON format. You might want to take a look around here https://github.com/devinit/datahub/blob/ceff0a8a140972674c95d4008cfc710912fdae5e/src/components/atoms/BaseMap/index.tsx#L460 I noticed this code doesn't account for the capital P in P20 for one of the layers.

**Comment by edwinmp** [comment]
@akmiller01 Alan had misspelled the indicator name in the code, so it the code that fetched data for these was never hit. He also hadn't included the subnational map's indicator. Changed https://github.com/devinit/datahub/blob/ceff0a8a140972674c95d4008cfc710912fdae5e/src/components/atoms/BaseMap/index.tsx#L477 to the code below and it works fine.
```
if (indicator === 'surveyp20' || indicator === 'survey_p20' || indicator === 'subnational_p20') {
      return BaseMap.fetchDataFromMapsWithCustomStyles(features);
}
```

**Comment by edwinmp** [comment]
@k8hughes Updated staging with a fully fixed version.

**Comment by k8hughes** [comment]
LGTM
