### ISSUE TITLE
Bug on chart lables

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#428]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The numbers 2015 and 2016 appear next to each other and running into each other.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://212.111.41.68:8080/country/zimbabwe 
2. Click on 'international resources'
3. Scroll down to 'in flows over time'
5. Change drop down and both 2015 and 2016 labels go entirely.

**Expected Behaviour**
I would expected that we just label 2015 and show that the graph is running past that point. We're only marking every5 year point on the bottom axis.

**Screenshots/GIF**
![screen shot 2018-10-04 at 12 09 59](https://user-images.githubusercontent.com/36768381/46471761-e3943280-c7d2-11e8-9169-fc12386eaea2.png)
![screen shot 2018-10-04 at 12 42 05](https://user-images.githubusercontent.com/36768381/46471821-15a59480-c7d3-11e8-97ad-ac36f216b466.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Firefox

**Environment/Server:**
<pre><code>
- [ ] Production
- [ x ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 08/10/2018

**Comment by edwinmp** [comment]
This was being caused by adding support for 2016. Since the gaps between years on the axis labels is set to 5 (2000, 2005, e.t.c), adding the extra year after 2015 created the need for both labels (2015 & 2016) to show, but with not enough space to show them.
To fix this, I changed the gap to 4 years. So we have 2000, 2004, e.t.c ... removes the need for showing 2015 and leaves enough space between the years.

**Comment by k8hughes** [comment]
LGTM!

**Comment by edwinmp** [comment]
Deployed!
