### ISSUE TITLE
Data hub reviews

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#86]
- [ ] Add bubble charts checklist

**Comment by epicallan** [comment]
current staging url: http://data.devinit.org:7777/

Whats ready for review?

Currently its mainly the global picture maps.

what doesn't work so great ?

- [ ] At the moment clicking to a country a profile wont take you to the country profile.
- [ ] some of the legend label values are wrong, its a rounding off issue will be corrected soon
i.e you may see 2k - 2k which should be 1.5k - 2k

**Comment by kb4777** [comment]
Hi @epicallan that's great, thank you. We'll get started on checking the global picture, thanks for flagging the issues in advance. Assume they'll also be fixed today?

**Comment by epicallan** [comment]
Hi @kb4777 Yes, they will be fixed by today.

**Comment by kb4777** [comment]
Brilliant, thanks @epicallan ! :-)

**Comment by epicallan** [comment]
FYI year slider wasn't working, had minor bug just fixed it.

**Comment by BeckyWillmoth** [comment]
@RebeccaHills are you able to review the branding this afternoon please?

**Comment by kb4777** [comment]
Hi @epicallan . Just spotted that the drop downs aren't working in the global picture

**Comment by kb4777** [comment]
@epicallan @BeckyWillmoth  I think it's that the black lettering is in a white font, so the drop downs are there you just have to hover over it

**Comment by epicallan** [comment]
FYI Spotlight on Uganda is also ready for review:  http://data.devinit.org:7777/spotlight-on-uganda

**Comment by epicallan** [comment]
@kb4777 https://github.com/devinit/datahub/issues/86#issuecomment-318648190 i know what you mean. You currently need to click on the current indicator instead of the arrow. This is actually being fixed. Will be fine in the next updates.

**Comment by kb4777** [comment]
Hi @epicallan . Oh yes, that is also an issue too. I was referring to something else! I'll make a to do list item here for you to look at on Monday

- [ ] The global picture drop down lists appear blank, only showing the first map name. This seems to be because the text is in white, so you can only see it when you hover over it. I can't take a picture because it only shows when the cursor is over the list

**Comment by RebeccaHills** [comment]
Hi @epicallan 

The Data Hub is looking great Allan, well done!

Here is my feedback on the global map (we've already discussed the gradients, but I've noted here too).

- [ ] Adjust gradients on all heatmaps so transition between middle colour and lightest and darkest are smoother. Some of the lightest shades could also be a little lighter (for example for humanitarian finance how does it look if we adjust lightest blue to blue 7 #bcd4f0?) (applies to all heatmaps)
- [ ] Poverty tab – “Number of people in the P20” dropdown – please switch the legend so the larger number (darker red) is on the bottom
- [ ] International finance tab – “Largest international resource flow” dropdown – please adjust to more muted tones of each (red 3, #f0826d), (yellow 3, #f9b865), (blue 3, #5da3d9), (orange 3, #f18e5e), (pink 3, #d64278), (purple 3, #a45ea1), (green 3,  #5ab88a), (grey 3, #847e84).
- [ ] Data revolution tab – all dropdowns – I am not sure what the dark grey represents (not in legend)
- [ ] Data revolution tab – please can we try 2 shades of green instead of three different colours – perhaps green 4 (#007851), green 1 (#109e68) and green 2 (#92cba9)

Thanks!

**Comment by RebeccaHills** [comment]
Hi @epicallan 

Apart from the same gradient issue, I only have one small bit of feedback on the spotlight:

- [ ] Population tab – “Total population” dropdown – the subheading, description and legend on the left seem to be too low down

Thanks again!

**Comment by epicallan** [comment]
FYI Number of uncoordinated appeals map doesn't work waiting for this to be resolved https://github.com/devinit/datahub-cms/issues/22

**Comment by kb4777** [comment]
Hi @epicallan (cc @BeckyWillmoth) This is a list of Global Picture issues that have been flagged from data-checking so far. There are some more things to add and checks are still ongoing. I'm cross-checking against things already mentioned above to avoid repeating, but apologies if I miss something.

- [ ] There is something going on with rounding. Firstly, not everything in new data hub is going to the same dp. E.g. 'Number of people living in extreme poverty' --> see DRC: 55.1 on old site, 55 on staging site. Secondly, the rounding is sometimes wrong. E.g on the same map, Kenya is 10 on staging, but 10.9 on old site (which should round to 11, not 10). These problems have appeared on multiple maps. 

- [ ] Top/bottom 10 rankings go from 0-9 instead of 1-10. Also, the top and bottom have switched places (bottom showing top and vice versa)

- [ ] 'i' button doesn't appear on any of the maps

- [ ] The last two words at the very bottom of the page – ‘privacy policy’ – appear in grey, where they used to be white. There should also be a space between 'our' and 'policy' 

- [ ] In the short paragraph at the top of the page, the last sentence 'Read more about the data hub' should be red hyperlinked and take you down the page to below the map.

- [ ] In the links at the bottom of the page, under 'Newsletter' heading, the words 'Development Initiatives newsletter' should be hyperlinked (in white, with a red hover). Similarly 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license' should also be a link. 

- [ ] At the bottom of the page, under the 'Sections' and 'Quick Links' headings, all the links point towards the DI blog. Also, the blog page only loads about half the time. The rest of the time it say 'Oops! That page can’t be found.' (This oops message also happens on the live data hub.)

- [ ] The four social media icons at bottom of the page all link to DI's twitter account. 

- [ ] The 'Methodology and Data' button below the video does not work

**Comment by kb4777** [comment]
Hi @epicallan . There's been some intermittent issues with the map loading toward the end of today (Tuesday). If we keep refreshing the page then we can get most of them to work eventually. Just flagging in case there's an underlying cause that needs solving. Thanks! cc @BeckyWillmoth

**Comment by epicallan** [comment]
FYI, I updated the staging url to http://212.71.254.23:9999/. Should work fine sorry about yesterday evening.

cc @kb4777

**Comment by kb4777** [comment]
Thanks @epicallan !

**Comment by kb4777** [comment]
Hi @epicallan. All these comments have now been transferred to the new issue cards, so could you please close this one? Thank you!
