### ISSUE TITLE
Country profiles checks

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#99]
TODO:
- [x] Correct number of decimal places shown in tabs
- [x]  legends on charts to be on the side instead of below
- [x]  income distribution chart on hover over event not working.
- [x] add missing text with in the 2 lower tabs 
- [x] spending allocation chart colors not as on live site
- [x] ODA breakdown missing in international resources charts
- [x] fix for countries whose government finance data is < 2015 eg brazil

**Comment by epicallan** [comment]
HOW MUCH GOVERNMENT REVENUE COMES FROM EXTERNAL GRANTS (AID)? 

The value on the staging site differs from whats on live coz the live one was using 'budget' data values instead of 'actual' in the domestic budgets data

I believe we should be using actual data values.
An analyst should weigh in
@BeckyWillmoth

**Comment by kb4777** [comment]
First glance issues:

**Comment by kb4777** [comment]
Other issues:

- [ ] When there is a typo, it generates a fake country page. E.g. 
![image](https://user-images.githubusercontent.com/25456036/29173430-2c49b4fc-7ddb-11e7-88a5-dae3b0c6b47a.png)

**Comment by kb4777** [comment]
Preliminary issues on 22/08/17
**- [ ] 'HOW MUCH DOES THE GOVERNMENT SPEND PER PERSON?' in 'Overview' banner is different for Turkey. (Also in Thailand, though this could be rounded)** 
**- [ ] 'HOW IS SPENDING ALLOCATED?' in 'Government Finance' banner is missing for Turkey. In Thailand it's there but looks different (a donut, with no values shown)**
**- [ ] 'HOW HAVE RESOURCE INFLOWS CHANGED OVER TIME?' in 'International Resources' banner has very different values when you hover, and slightly different shapes too (particularly for official). Tested in Turkey, Thailand, Kenya**
- [ ] the 'i' button info for  'Government Finance' banner is wrong for Turkey, Kenya
- [ ] Government finance blue boxes have largest at top, smallest at bottom, instead of other way around.
- **[ ] Still in blue boxes, total financing for Turkey is 0, should be 7.2bn. Total expenditure says 140.9bn rather than 174.5 bn. There are also issues in Kenya, particularly for financing**
- [ ] Budget type drop downs say short hand, e.g. 'Proj' instead of full word 'Projected' 
- [ ] Resource flows in wrong order, should be official, then commercial, then private 
- [ ] The inflows/outflows charts at the bottom of 'International Resources' tab land on Inflows option rather than outflows, but the left hand title says outflows and stays on that when flicking between.
- [ ] the boxes on the righthand side, for the all resources breakdown, are all in the wrong order
- [ ] (small issue) the year scroller on the left hand chart is very tall

Hi @BeckyWillmoth and @epicallan . I've gone through Turkey fully and a bit of Thailand and Kenya to compare, and there are some issues that include wrong/missing data. I've put these 4 in bold. Other problems are more visual, a little broken functionality.  Need to decide if these should be fixed before proceeding...

**Comment by kb4777** [comment]
Hi @epicallan thanks for your response above to the donut question. Definitely sounds like an improvement but I'm a bit confused as there isn't 2015 projected data for Thailand (Uganda is the only country that ever has both actual and budget data for the same year) so don't see how it could have changed?

**Comment by epicallan** [comment]
- [ ] years missing on area line chart in overview tab for donor countries: http://212.71.254.23:8888/country/spain

**Comment by remilsg** [comment]
The Issues listed below are all High priority ones

- [ ] in general, the charts are not responsive to zoom + not usable in mobile version : they don’t adjust correctly (Population tab: when zooming in, the two charts on that tab start to overlap) [screenshot (both mobile and computer)]

- [ ] ‘government finance’ hyperlink below introductory sentence is misspelt + no letter should be capitalised in the hyperlink  ‘International Resources’

- [ ] when selecting a country from the dropdown, the display on the map does not change (i.e. the focus is on the same country as before) **add screenshot**

- [ ] data sources (bottom of the page): only one appears in staging version

**Top 5 banner tabs**

- [ ] Banner ‘international resources’, “Resource inflows/outflows over time”: there is a legend below the graph (only in staging version) 
          “How much aid does XXX allocate”/”How much aid is allocated to XXX”:  Country name should be written in capital letters + When the live site shows ‘0.0%’, staging site shows ‘No Data’ (e.g. China)

- [ ] i buttons (info boxes): - 'income distribution per quintile': shows a different year (e.g.  shows ‘data is for 2015...’ instead of ‘for 2014’)  
                - ‘what is the total population’: year when the data was extracted is not precised in the info box (i.e. the sentence 'data is for XXXX' does not appear)

**International Resources Tab Option** 

- [ ] content of this tab should appear automatically (without needing to click on the tab title)

- [ ] inflows vs. outflows:  - values don't come up when hovering over the graph   
                                        - Flow Detail name: colour should be lighter (see screenshot below)
                                        - i button (info box): text is very different between the 2 versions (staging version: text is the same as for graph ‘How have Resource inflows changed over time’, in the top banner tab ‘International Resources’)  
                                         - share this chart button: ‘inflows vs. outflows’ -> does not work (pop-up appears, but links don’t work)    
![f2efde522c3b608529423a952da87f76ad1a9d342a003ce4f9 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/31883624/30321889-8f558466-97af-11e7-8131-e0ffe7ac9bab.jpg)
                                          
           

- [ ] In Detail International Resources: 
           - The Mix of Resources in XXX: boxes are not arranged in the same way                                       
                          live -> from large in  top-left corner, small in bottom-right corner                           
                          staging -> large bottom-left, small top-right corner 
![c8274a022363b226fe2fb0bdab89942b8e5a75b88bc1b6328f pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/31883624/30322452-6bb5145c-97b1-11e7-9e95-9f07c3d236e8.jpg)
                                  


Donor countries have recipient country banners. E.g. showing poverty and government finance lthough they should not; should only show Overview, Population, and international resources
+ the content of the banners is the same as for recipient countries (e.g. the banner ‘overview’ shows available resources instead of government spending per person per year; Banner ‘international resources’, graph “resource inflows over time”: title should be ‘resource outflows over time’) [add screen shot(s)]  The graph ‘What’s the Mix of resources?’ does not appear. [add screenshot]banner ‘international resources’: “How much aid is allocated to XXX ?”: The question should be: “How much aid does XXX allocate ?”
Says ‘no data’ [add screenshot] 

i button: HIGH - absent ‘As a share of GNI, How much aid is allocated to XXX’ (banner tab ‘International Resources’)
                 - Info for ‘resource outflows over time’ is wrong (in both live and staging version !)
Should show: ‘Estimates of International Resource Flows to Developed Countries.’ (currently shows: ‘Estimates of Int Resource Flows from Developed Countries)

Recipient 
HIGH Banner ‘Poverty’: “Is Poverty reducing over time?” -> Unit (%) is not shown in hover box
HIGH - i button: - ‘How many of the poorest people’, ‘What resources are available? International’, ‘Depth of Poverty’, ‘What’s the Mix of Resources?’: year not precised
               - ‘As a share of GNI, how much aid is allocated to XXX?’: unit is wrong in info box (should be %, but it is US$) + sources are different between live and staging version
HIGH - the header ‘financing’ appears below the graph (in both versions): does not look right 
HIGH - rounding is different for some data (e.g. Ghana; Total revenue & Grants -> Revenue: live 6.4bn [89%], staging 6.5bn [90%])
- when changing currency in the dropdown boxes, the symbol does not change within the blue boxes within the chart (values do change though);
![5291ccbe10d798e9e5f8c901effd490b06a1d75faa3edf8449 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/31883624/30318049-e0d373c2-97a3-11e7-9915-1d96adc6e8d0.jpg)

**Comment by remilsg** [comment]
The Following Issues Are Medium & Low Priority 
### General
**Top 5 Banner Tabs**  

- [ ] MEDIUM When a country has a two word name (Russian Federation, United Kingdom etc) it appears hyphenated in the profile title [add screen shot]  + Every word appears  on a new line 
When a country name is abbreviated (e.g. CAR, DRC, UAE) , it needs to be capitalised (e.g. USA: country name currently displayed as Usa)
 countries with an apostrophe in the name have an issue (e.g. Cote d’Ivoire becomes Cote Divoire) ![image](https://user-images.githubusercontent.com/25456036/30212477-163fe914-949d-11e7-90ef-ae8cdc5f0f86.png)
![capture d oussama finest girl tmtc special unit request so irregular](https://user-images.githubusercontent.com/31883624/30333058-ec6b2ab0-97d3-11e7-89c1-5560762327d0.PNG)
- [ ] MEDIUM Banner ‘overview’, “Government Spending per Person”:                                                         
              when no data is available -> live shows ‘no data’; staging shows ‘PPP$ No Data’ (e.g. Hungary)
- [ ] LOW: Banner ‘population’: - the font and colour for ‘Urban vs. Rural Split’ is not the same (in the live version: Urban is written in red, and Rural in blue; in the staging version, all the text is in black) 
![urban topito tmtc](https://user-images.githubusercontent.com/31883624/30333206-4e609d2c-97d4-11e7-85c2-3a2384753b21.PNG)
- [ ] MEDIUM Banner 'overview': "Government spending per person" -> data shown without thousand separator (e.g. PPP$ 1116 instead of PPP$ 1,116) 
- [ ] LOW lines for graphs in the top 5 banner tabs look smoother in staging version (no angles) 
![donor countries banner](https://user-images.githubusercontent.com/31883624/30334420-7d07fadc-97d7-11e7-8ef3-5c76055c6654.png)

- [ ] MEDIUM Graph ‘How is income distributed’: the sentence ‘bottom quintile has X% of the income” is very small relative to the size of the graph in staging version

**International Resources Tab Option** 

- [ ] LOW 'Inflows vs. Outflows': in live version, official flows are the first category (on top); in the staging v, it is Commercial flows 
- [ ] LOW 'In Detail Int Resources': graph title in dropdown box: "Outflows leaving France" (staging v) ≠  "Outflows from France" (live); 
- [ ] MEDIUM The year slider is too tall on the ‘flows over time’ chart + there should be no border on the year ring + top of the ring is cut off + there is agap between the circle and the line [add screenshot with zoom]
- [ ] LOW ‘In Detail Int Resources’, “The  mix of Resources in *year*”: year is written in black font in staging version (red in live version)  
- [ ] MEDIUM  when hovering on the graph to the left, detailed values appear in a box at the top: the rightmost content of this box cannot be read for 2014/15, as it disappears under the graph to the right **[add screenshot from mac]**: hover box would need to appear in front of everything else to be readable                                                                                                                                                                                                                                                                         
- [ ] LOW the sub-heading text (value, %) in the boxes appears smaller in the staging version, so it is harder to read

### Donor Countries
- [ ] MEDIUM graph inflows over time (tab international resources); colour for 'capital repayments on OOFs' and 'interest payment on OOFs' is the same **[screenshot]**: one of them need to be a different shade of the blue

### Recipient Countries 
**Government Finance Tab Option** 
- [ ] MEDIUM the year should be precised every 5 year in the x axis for the line chart; + make sure they don’t overlap [addscreenshot] e.g. Mali
- [ ] Bolivia: Country name is different: live -> ‘Bolivia, Plurinational State of’; staging -> ‘Bolivia’

**Top 5 Banner Tabs** 
- [ ] LOW For the graphs in the top 5 banner tabs, Overview tab, graph ‘average income over time’: the colour is wrong/not the same as the red used for the rest of the tab; colour should be code #e84439
- [ ] LOW Mix of resource chart (tab international resources), text colour should be white instead of black in ‘private development assistance’ box

**Comment by remilsg** [comment]
- [ ] LEAVE FOR NOW; Graph 'Inflows vs. Outflows': when value is 0, graph shows '0.0' -> the extra decimal point is not necessary 
e.g. Hungary, Lithuania, Romania
![snip snip je pleure](https://user-images.githubusercontent.com/31883624/30754006-025cbe14-9fb9-11e7-868b-167245dee78c.PNG)

**Comment by epicallan** [comment]
Ghana issue about values not rounding off on staging as on live;

The values round off correctly. 

The data on live seems to be old since it has an extra level called 'other no info' which no longer exist in the database. It seems it was merged with revenue which makes it different from staging.
![screen shot 2017-09-27 at 13 18 49](https://user-images.githubusercontent.com/6281527/30908829-8673b046-a387-11e7-8e72-cfaf23d9d888.png)
<img width="808" alt="screen shot 2017-09-27 at 13 27 03" src="https://user-images.githubusercontent.com/6281527/30908851-9b415898-a387-11e7-9abd-c834e05e998d.png">

cc @BeckyWillmoth
